name: Run Main Script Every 2 Hours

on:
  schedule:
    - cron: '0 */1 * * *' # Run every 1 hours

  workflow_dispatch:

jobs:
  run-main-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Specify the version of Python you need

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install Tesseract
      run: |
        sudo apt-get update
        sudo apt-get install tesseract-ocr -y

    - name: Set up Tesseract PATH
      run: |
        echo "/usr/bin/tesseract" >> $GITHUB_PATH

    - name: Run Python Script
      run: python main.py