name: Run Main Script Every 1 Hours

on:
  schedule:
    - cron: '0 */2 * * *' # Run every 1 hours

  workflow_dispatch:

jobs:
  run-main-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9' # Specify the version of Python you need

    - name: Install Tesseract
      run: |
        sudo apt-get update
        sudo apt-get install tesseract-ocr -y
        pip install pytesseract

    - name: Check Tesseract Version
      run: tesseract --version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Python Script
      env:
        GITHUB_TOKEN: ${{ secrets.TOK }}
      run: python main.py